default: &default
  adapter: postgresql
  encoding: unicode 
  database: <%= ENV["PG_DATABASE"] %>
  pool: 5
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>

test:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>

production:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>