default: &default
  adapter: postgresql
  encoding: unicode 
  pool: 5

development:
  <<: *default
  username: postgres
  password: admin
  database: rails_blog_dev

test:
  <<: *default
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  database: <%= ENV["PG_DATABASE"] %>

production:
  <<: *default
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  database: <%= ENV["PG_DATABASE"] %>